# Generated by Django 4.0.1 on 2022-02-20 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_instituicaofk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='InstituicaoFk',
            new_name='Instituicao',
        ),
    ]
